### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by bymaximus** [Captain-Of-Coit/cs2-vehicle-counter#1]
Hello, can we have a released dll for BepInEx 6? 
The one at thunderstore.io version seems using version 5

**Comment by Captain-Of-Coit** [comment]
Yes, Thunderstore version is for Bepinex 5.

You should be able to download `build-code-6` from here: https://github.com/Captain-Of-Coit/cs2-vehicle-counter/actions/runs/6999793432 That file is built with Bepinex 6.

Let me know if it doesn't work

**Comment by bymaximus** [comment]
Thank you, it works, but needs to put the HookUILib.dll inside the plugin folder otherwise it throws reference error
